image: python:3.11

stages: #pipelines listed in the documentation
- validator #already implemented
- lint
- test
- build
- documentation

include:
  - remote: 'https://gitlab.in2p3.fr/informatique-des-deux-infinis/npac/validator/-/raw/main/validator_template.yml'
    inputs:
      package_name: 'npac_calibration'


before_script:
  - python --version ; pip --version  # For debugging
  - pip install pdm
  - pdm install


lint:
  script:
    - pdm run black --check src/
    - pdm run flake8 src/


test:
  script:
    - pdm run pytest --doctest-modules .


build-job:
  stage: build
  before_script:
    - pip install -U pip
    - pip install pdm
    - pdm install

    # create the config file used to publish the package
    - |
      cat <<EOD > .pdm-config.toml
      [repository.gitlab]
      url = "https://gitlab.in2p3.fr/api/v4/projects/31456/packages/pypi"
      username = "__token__"
      password = "$DEPLOY_TOKEN"

      [pypi.gitlab]
      username = "__token__"
      password = "$DEPLOY_TOKEN"

      EOD

  script:
    # build and publish the package to the local Gitlab registry
    - pdm -c .pdm-config.toml publish --repository gitlab
  only:
    # only run the job when a new tag is pushed
    - tags

pages:
  stage: documentation
  script:
    - pdm run sphinx-build -b html doc/source public
  artifacts:
    paths:
      - public
  